services:
    changedetection:
      image: ghcr.io/dgtlmoon/changedetection.io
      container_name: changedetection
      hostname: changedetection
      environment:
        - TZ=Europe/Berlin
        - BASE_URL= https://URL/
        - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000
      volumes:
        - changedetection-data:/datastore
      ports:
        - 5000:5000
      restart: unless-stopped
    playwright-chrome:
        hostname: playwright-chrome
        image: dgtlmoon/sockpuppetbrowser:latest
        restart: unless-stopped
        tmpfs:
          - /tmp    # This just keeps tmp data from being written to disk
        environment:
            - SCREEN_WIDTH=1920
            - SCREEN_HEIGHT=1024
            - SCREEN_DEPTH=16
            - MAX_CONCURRENT_CHROME_PROCESSES=10
            - STATS_REFRESH_SECONDS=120 # Default is 3 seconds which is way too much

volumes:
  changedetection-data:
