version: "3"
services:
    jdownloader-2:
        container_name: jdownloader-2
        ports:
            - 5800:5800
        volumes:
            - config:/config
            - /mnt/data:/output:rw
        environment:
            - KEEP_APP_RUNNING=1
        image: jlesage/jdownloader-2
volumes:
    config:
